eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  #    hostname: localhost
  client:
    #是否将eureka自身作为应用注册到eureka注册中心
    register-with-eureka: false
    #为true时，可以启动，但报异常：Cannot execute request on any known server
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/

#基本信息
info:
  description: 平台注册中心
  version: v1.0
  author: 技术部