eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
server:
  tomcat:
    # 最大连接线程数，即：并发处理的最大请求数，默认值为 75
    maxConnections: 3000
    # 允许的最大连接数，应大于等于 maxProcessors ，默认值为 100
    acceptCount: 1000
    # 编码方式
    uri-encoding: UTF-8

application:
  base-package: com.js

logging:
  config: classpath:logback-spring.xml

#基本信息
info:
  description: 动态配置中心
  version: v1.0
  author: 技术部